### PR TITLE
Initial commit for request for package paraview!

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
Looks like we have an issue with the last build:

```bash
==> Updating view at /opt/view
The command 'docker-shell cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y' returned a non-zero code: 1
```
@alecbcs have you seen this before?

**Comment by alecbcs** [comment]
Yep, it looks like Spack isn't building GCC with the proper plugin compatibility. Looks like they actually maybe just pushed a fix for this in the main spack repo! (spack/spack#22989)

**Comment by alecbcs** [comment]
We might have to wait for the nightly spack container to rebuild but maybe trying this build again tomorrow might work.

**Comment by vsoch** [comment]
gotcha! I'll pull the updated one and try again tomorrow.

**Comment by vsoch** [comment]
ah I guess it didn't work. It's no worries, I can use the paraview container from nvidia's cloud.

**Pull request closed without merging**
