### PR TITLE
adding packages for ascent

### PR DESCRIPTION
**Pull request by vsoch**
I want to test adding two again - these are very heavily used at the lab so I'm thinking we should give them a go!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@alecbcs I think I messed this up - so we can only do one package per PR, right?  I can split this into two, not sure why I already forgot our conversation this morning... it must be Friday!

**Comment by alecbcs** [comment]
Hahaha no worries. Yep only 1 independent package per PR at the moment.

**Comment by alecbcs** [comment]
Looks like this one is failing because of the same `version(master)` error as the other PR.

**Comment by alecbcs** [comment]
Looks Good!

**Pull request merged**
