### PR TITLE
Fix samtools dependency

### PR DESCRIPTION
**Pull request by brighill**

### CODE REVIEW

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Thank you @brighill !

**Comment by alecbcs** [comment]
@brighill looks great! Do you also want to submit these updates as PR to the main Spack repository? If not I can bundle with another push to Spack but I don't want to take credit for your work!

**Comment by vsoch** [comment]
I can also offer to help with that if you are busy with school @alecbcs!

**Comment by alecbcs** [comment]
@vsoch Sure! Feel free to push any changes from Autamus to Spack! Just @ me so that I can keep track of which packages have already been submitted.

**Pull request merged**
