### PR TITLE
Initial Commit of apfel

### PR DESCRIPTION
**Pull request by alecbcs**

### CODE REVIEW

**Comment by alecbcs** [comment]
@vsoch what do you make of this? It seems like it must be built with python instead of python just being a variant? I'm I missing something?

**Comment by vsoch** [comment]
if Python is a variant there must be a use case of not wanting it - but I don't know what that would be :) I would just add +python (this line) https://github.com/autamus/registry/pull/99/files#diff-cf0503e86d12eb335abda11215497c99b55d68409cdb6d009bff1e13e63424b1R23.

**Comment by alecbcs** [comment]
Right, I think the problem might be that right now we have a good way of defining custom Spack install options. This is something I'm currently working on for when we add the ability for custom multi-package containers. I'll hold off on this PR  until then and then I'm guessing we'll just make an apfel container with this package installed.

**Comment by alecbcs** [comment]
I'm going to close this PR until we've implemented multi-package support if that's alright.

**Pull request closed without merging**
