### PR TITLE
Adding vim package and testing new mutlistage builder

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@alecbcs is this error something about being a PR (and not the main branch) or something about libabigail?

```

#10 [builder 4/7] RUN mkdir /opt/spack-environment &&  (echo "spack:" &&   echo "  specs:" &&   echo "  - libabigail" &&   echo "  view: /opt/view" &&   echo "  packages:" &&   echo "    all:" &&   echo "      target:" &&   echo "      - x86_64" &&   echo "  config:" &&   echo "    compiler:" &&   echo "      target: x86_64" &&   echo "    install_missing_compilers: true" &&   echo "    install_tree: /opt/software" &&   echo "  mirrors:" &&   echo "    autamus: s3://autamus-cache" &&   echo "  concretization: together") > /opt/spack-environment/spack.yaml
#10 sha256:26d7918e93b11177ef4b91cd40218a0aad591164d4eac013a2bfd9c6beb63ddc
#10 DONE 0.5s

#11 [builder 5/7] RUN  cd /opt/spack-environment && spack env activate . && export SPACKMON_USER=$(cat /run/secrets/su) && export SPACKMON_TOKEN=$(cat /run/secrets/st) && spack install --fail-fast && spack gc -y
#11 sha256:bf5bb5cd039906de4b62a2395e3915cd72ab3e2987565071ad3b119179af7734
#11 0.828 cat: /run/secrets/su: No such file or directory
#11 0.830 cat: /run/secrets/st: No such file or directory
#11 5.340 gpgconf: socketdir is '/root/.gnupg'
```
I didn't change anything about the main container build (but hopefully I didn't introduce a bug!) When you have some time this week could you take a look?

**Comment by alecbcs** [comment]
@vsoch this looks good! I'm going to hold off on merging until the multi-stage builder has been added to the builder so that we can continue to use the docker image instead of Dockerfile. But otherwise I don't see any blockers here.

**Comment by vsoch** [comment]
yep that sounds good.

**Comment by alecbcs** [comment]
@vsoch since we've moved over to `autamus/chef` do we still want to pursue the multi-stage layers?

**Comment by vsoch** [comment]
I think so - it’s a totally different idea. But since it’s experimental we could put it somewhere else if you like!

**Comment by alecbcs** [comment]
What if we keep the branch open on this repository but close this pull request for now? Then when we come back to the idea we can reopen this and merge it into Autamus when we're ready to build layer containers?

**Comment by vsoch** [comment]
That works for me! We can also just keep the PR open for better visibility (but not merge it). Your call!

**Comment by alecbcs** [comment]
I'm going to close it for now, just since I've been treating the PRs on this repository like a To Do list with all of the updates. But with the branch still on the repository let's not forget about it! (We could also open up the idea of layers as an issue/discussion post for the future to see if others are interested.)

**Pull request closed without merging**
