### PR TITLE
Adding mpich, initial package

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
And here is matching PR in spack: https://github.com/spack/spack/pull/23865

**Comment by vsoch** [comment]
@alecbcs how do we add a variant? Locally on the command line I'd just do:

```bash
spack install mpich+debug
```

**Comment by alecbcs** [comment]
@vsoch should be fixed with the latest push to Builder! I'd forgotten to normalize the names from the Spack Environment when reading from the YAML. We're now grabbing the name of the package correctly and separating it from the variant info.

**Comment by vsoch** [comment]
@alecbcs good to merge here? I can test this container with the build bases!

**Comment by alecbcs** [comment]
Absolutely! Didn't want to prematurely accept if you were still testing changes. Will merge it now! Looks good to me!

**Review by alecbcs — APPROVED** [review]
Looks good to me!

**Comment by alecbcs** [comment]
@vsoch once this finishes if I don't catch it you might have to make the container public.

**Comment by vsoch** [comment]
I'll keep watch for it! I want to use the container today so I'm good with watching :)

**Pull request merged**
