### PR TITLE
adding package for axom

### PR DESCRIPTION
**Pull request by vsoch**
This is the same PR, but cleaning up the git history.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by alecbcs** [comment]
@vsoch ahh! I'm still working on adding `version(master)` support to `go-parspack` so right now the version is coming up as N/A which Spack doesn't know how to handle. I'll work on adding in this support, in the mean time you should be able to fix this error by removing the master version from the spec file.

**Comment by vsoch** [comment]
Ahh so sorry! Just ignore these PRs for now, I didn’t mean to add any stress! I’ll hold off adding more packages. Sorry about that!

**Comment by alecbcs** [comment]
@vsoch haha no no, please keep submitting packages! Sorry I meant that "ahh!" like "ahh shucks I forgot to work on `go-parspack`". (Also hell yeah I'm an old man at heart and use the phrase shucks lol.)  Absolutely no added stress this is really fun testing the system out and fixing bugs! I just submitted updates for `go-parspack`, `binoc`, and `build-config` so we should we all good for packages that include a git branch version tag. Test away and I look forward to seeing what else we can build!

**Comment by alecbcs** [comment]
Looks like Axom is looking for the zlib object file where the general lib directory is? This is probably something we should report to the Spack team/Axom maintainer. 

```
   >> 410    ld: cannot find /opt/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-
            7.5.0/zlib-1.2.11-fz2bs562jhc2spgubs3fvq25g3qymz6x/lib: File format
             not recognized
```

**Comment by vsoch** [comment]
https://github.com/spack/spack/issues/22280

**Pull request closed without merging**
