### PR TITLE
Initial inclusion of Singularity

### PR DESCRIPTION
**Pull request by vsoch**
This is also a test to see what happens if two packages are included. If it's not a good idea, I'll re-open them separately (but it would be nice to be able to add more than one per PR!)

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by alecbcs** [comment]
@vsoch Huh? Looks like BuildConfig maybe tried to parse of the patches? I'll take a look at this.

**Comment by vsoch** [comment]
Sounds good! Looks like we don’t have a parsers_loaded config option exposed too.

**Comment by alecbcs** [comment]
Ooo BuildConfig freaks out because of the commit having singularity and singularity-legacy. When two packages are submitted in the same PR it assumes they must be dependencies of each other and since these two aren't it can't decide which to build. I'd try making another PR for singularity-legacy and just include singularity in this one.

**Comment by vsoch** [comment]
Hmm, so the commit history has to be perfect for it to work? That's a pretty high expectation for contributors - can binoc be more flexible?

**Comment by alecbcs** [comment]
> Hmm, so the commit history has to be perfect for it to work? That's a pretty high expectation for contributors - can binoc be more flexible?

Haha no it should be able to go back and check all of the files changed in the PR. Looks like it was actually creating blank packages for the patches and that was causing the errors.

Wow not the best first impression lol, first two packages you submit and they expose bugs/things I hadn't thought about. Well keep em' coming!

**Comment by vsoch** [comment]
Haha, bugs are not bad! I’m choosing edge cases specifically to find them.

**Comment by alecbcs** [comment]
@vsoch should we not attempt to strip the binaries?

```yaml
spack:
  specs:
  - singularity

  container:
    # Select the format of the recipe e.g. docker,
    # singularity or anything else that is currently supported
    format: docker

    # Sets the base images for the stages where Spack builds the
    # software or where the software gets installed after being built..
    images:
      os: "ubuntu-bionic"
      spack: develop

    # Whether or not to strip binaries <--- ?
    strip: true
```

**Comment by vsoch** [comment]
If strip means remove debug information, I'd say we should not - because we are badly needing debug information for our work in BUILD SI, and most of them aren't built with it.

**Comment by alecbcs** [comment]
Okay it looks like that might be why the build failed?

**Comment by vsoch** [comment]
Yeah let's make strip false, it seems better to not try to mess with the finished binary!

**Comment by alecbcs** [comment]
Woo! @vsoch merge when ready.

**Comment by vsoch** [comment]
I am ready!!

**Comment by vsoch** [comment]
Running here -> https://github.com/autamus/registry/runs/2099391805?check_suite_focus=true !

This could actually be a really useful thing to not strip them. I'm curious if that means that they are built with debug info (and then it's not stripped).

**Pull request merged**
