### PR TITLE
Spell checking

### PR DESCRIPTION
**Pull request by bjoyce3**
No idea why the dyslexic is doing that :P

### CODE REVIEW

**Comment by bjoyce3** [comment]
Uh, looks like it buildings a container if we edit the README :|

**Comment by vsoch** [comment]
@bjoyce3 I think that's probably because the workflow recipe is instructed to run for PRs against main, which makes sense if we want to eventually merge into that. If you look at the message, binoc reports not being able to find a package and exits with an error code:

```
2021/03/15 04:19:43 could not find head package to update
```
There are a few ways we could tweak this - I don't think we'd want to change the branch rules (but we could) but other ideas might be:

1. have the trigger be applying a label instead of opening a PR, although this adds one extra step for the maintainer to open the PR and then apply the label, it would ensure that all other PRs don't get the workflow run.
2. Have binoc exit with error code 0 and a message back here that there aren't any recipes detected. This comes down to deciding if we think a state of "no recipes found!" is erroneous or not.

**Comment by alecbcs** [comment]
It'd be a bit of extra work, but we could create a third workflow that'd run on every pull request, figure out if any files within the `spack/` directory have changed, and if so automatically tag the PR as a package build. Otherwise I expect that 99% of the pull requests to this repository will be package updates/new packages.

**Comment by bjoyce3** [comment]
Well I'm up for whatever, but some thoughts:
- I'd hate for the automaticitude of Autamas to be hampered by applying labels by hand. Do want to have humans in the loop, but probably not for busy work.
- Exiting with error code 0 based on whether the spack/ directory has changes makes a lot of sense to me. 
- I suspect there will be many of these cases where a not spack/ thing will change, and would rather not present errors to people contributing in the future. But maybe that needs to be thought out more. Just a gut feeling.

**Comment by alecbcs** [comment]
Okay gotcha. I'll start drafting up some plans for how we can tell the workflow to skip steps/jobs if a PR doesn't change a package. Until then I'll go ahead and merge these documentation changes.

**Pull request merged**
